import EditorHeader from "@/components/client/Editor/EditorHeader";
import { DragDropProvider } from "@/context/DragDropContext";
import { HtmlCodeGeneratorProvider } from "@/context/HtmlCodeGenerator";
import { ScreenSizeProvider } from "@/context/ScreenSizeContext";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Editor | EmailWiz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ScreenSizeProvider>
      <HtmlCodeGeneratorProvider>
        <DragDropProvider>
          <html lang="en">
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
              {children}
            </body>
          </html>
        </DragDropProvider>
      </HtmlCodeGeneratorProvider>
    </ScreenSizeProvider>
  );
}
